### PR TITLE
loosen network dependency

### PR DESCRIPTION
**Pull request by qnikst**
[Review on Reviewable](https://reviewable.io/reviews/tweag/network-transport-zeromq/33)

### CODE REVIEW

**Comment by facundominguez** [comment]
How about removing the upper bound instead?

**Comment by qnikst** [comment]
I'm not a big fun of not having upper bound, but it seems reasonable in this case, fixing.

**Comment by qnikst** [comment]
done

**Comment by facundominguez** [comment]
:+1:

**Pull request merged**
